# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c6c478016b6e726b5d695e35159b6c2a9cbba303819d2baf52ca8dda2292af6079449ec5e80472684329c7698c68d791d25b6cdcc064872f05cf74f3c03c3b7

test:
  secret_key_base: 45fe8cbd7ed953ffbd2a4cafca334d0c4199b4e45237eeaf369f3b482fac899e3641b641006ac73a56eced937ca8d2a263d07c74d956e0d364d41b025dd6a84f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
